// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ynlebwtutvyxybqgupke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlubGVid3R1dHZ5eHlicWd1cGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NDA0NTMsImV4cCI6MjA3OTExNjQ1M30.-Mgv5jFyg0k1723-LCj2h-teE-eblUGXn8XorgyNn4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);